---
version: "2.0"

services:
  web:
    image: avaplatform/avalanchego:latest
    expose:
      - port: 9650
        as: 9650
        to:
          - global: true
      - port: 9651
        as: 9651
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - ./avalanchego --network-id=fuji --http-host=0.0.0.0 --http-allowed-hosts=*
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 8GB
        storage:
          - size: 100Gi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
deployment:
  web:
    dcloud:
      profile: web
      count: 1
